<?php
/**
 * nexvue-jwks.php — public JWKS for MediaMTX JWT auth (no session required).
 *
 * MediaMTX polls this once (cached) via authJWTJWKS. Serves the RSA public
 * key from /var/lib/nexvue/auth/jwks.json (generated by auth_ensure_keys).
 */

declare(strict_types=1);

require_once __DIR__ . '/nexvue-auth-lib.php';

header('Content-Type: application/json');
header('Cache-Control: public, max-age=60');

try {
    $keys = auth_ensure_keys();
    echo json_encode($keys['jwks'], JSON_UNESCAPED_SLASHES);
} catch (Throwable $e) {
    http_response_code(500);
    echo json_encode(['keys' => [], 'error' => 'jwks unavailable']);
}
